# Generated by Django 5.2.11 on 2026-02-17 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='person_images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='timelineevent',
            name='tags',
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='people',
            field=models.ManyToManyField(blank=True, related_name='events', to='timeline.person'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
