# Generated by Django 5.2.11 on 2026-02-18 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0003_location_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='timeline.timeline')),
            ],
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='timelines',
            field=models.ManyToManyField(blank=True, related_name='events', to='timeline.timeline'),
        ),
    ]
