# Generated by Django 5.2.11 on 2026-02-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0004_timeline_timelineevent_timelines'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineevent',
            name='link',
            field=models.URLField(blank=True, help_text='Optional external link', null=True),
        ),
    ]
