# Generated by Django 5.2.11 on 2026-02-18 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0005_timelineevent_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='link',
            field=models.URLField(blank=True, help_text='Optional external link', null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='link',
            field=models.URLField(blank=True, help_text='Optional external link', null=True),
        ),
    ]
