# Generated by Django 5.2.11 on 2026-02-22 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0008_eventimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='disambiguation',
            field=models.CharField(blank=True, help_text="e.g. 'The Younger' or 'Farmer' to distinguish from others with the same name", max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='PersonRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('parent', 'Parent'), ('child', 'Child'), ('spouse', 'Spouse'), ('sibling', 'Sibling'), ('other', 'Other')], max_length=20)),
                ('start_date', models.DateField(blank=True, help_text='e.g. Marriage date', null=True)),
                ('end_date', models.DateField(blank=True, help_text='e.g. Divorce date', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('from_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to='timeline.person')),
                ('to_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to='timeline.person')),
            ],
        ),
    ]
