# Generated by Django 5.2.11 on 2026-02-23 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0009_person_disambiguation_personrelationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='ceased_date',
            field=models.DateField(blank=True, help_text='When this location ceased to exist or was destroyed', null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='established_date',
            field=models.DateField(blank=True, help_text='When this location was founded or built', null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='birth_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='births', to='timeline.location'),
        ),
        migrations.AddField(
            model_name='person',
            name='death_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deaths', to='timeline.location'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='is_auto_generated',
            field=models.BooleanField(default=False, help_text='True if created automatically (e.g. births/deaths)'),
        ),
    ]
