# Generated by Django 5.2.11 on 2026-02-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0010_location_ceased_date_location_established_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='ceased_date_display',
            field=models.CharField(blank=True, help_text="e.g. 'circa 1900'", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='established_date_display',
            field=models.CharField(blank=True, help_text="e.g. 'circa 1830'", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='birth_date_display',
            field=models.CharField(blank=True, help_text="e.g. 'circa 1830'", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='death_date_display',
            field=models.CharField(blank=True, help_text="e.g. 'circa 1900'", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='personrelationship',
            name='end_date_display',
            field=models.CharField(blank=True, help_text="e.g. 'circa 1900'", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='personrelationship',
            name='start_date_display',
            field=models.CharField(blank=True, help_text="e.g. 'circa 1830'", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='end_date_display',
            field=models.CharField(blank=True, help_text="e.g. 'circa 1900'", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='start_date_display',
            field=models.CharField(blank=True, help_text="e.g. 'circa 1830'", max_length=255, null=True),
        ),
    ]
