# Generated by Django 5.2.11 on 2026-02-23 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0011_location_ceased_date_display_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ViewSettings',
        ),
    ]
