# Generated by Django 5.2.11 on 2026-02-23 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0012_delete_viewsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='timeline',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='timelineevent',
            options={'ordering': ['-start_date', 'title']},
        ),
    ]
