# Generated by Django 5.2.11 on 2026-02-24 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0016_timelineevent_source_citation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='cloned_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='timeline.timeline'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='cloned_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='timeline.timelineevent'),
        ),
    ]
