# Generated by Django 5.2.11 on 2026-02-24 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0017_timeline_cloned_from_timelineevent_cloned_from'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelineevent',
            name='source_citation',
        ),
        migrations.AddField(
            model_name='location',
            name='ceased_date_source_page',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='coordinates_source_page',
            field=models.CharField(blank=True, help_text="e.g. 'p. 142'", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='established_date_source_page',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='birth_date_source_page',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='birth_location_source_page',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='death_date_source_page',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='death_location_source_page',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='end_date_source_page',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='location_source_page',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='start_date_source_page',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, help_text='Link to the source online', null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('publication_date', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='location',
            name='ceased_date_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='timeline.source'),
        ),
        migrations.AddField(
            model_name='location',
            name='coordinates_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='timeline.source'),
        ),
        migrations.AddField(
            model_name='location',
            name='description_sources',
            field=models.ManyToManyField(blank=True, related_name='+', to='timeline.source'),
        ),
        migrations.AddField(
            model_name='location',
            name='established_date_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='timeline.source'),
        ),
        migrations.AddField(
            model_name='person',
            name='birth_date_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='timeline.source'),
        ),
        migrations.AddField(
            model_name='person',
            name='birth_location_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='timeline.source'),
        ),
        migrations.AddField(
            model_name='person',
            name='death_date_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='timeline.source'),
        ),
        migrations.AddField(
            model_name='person',
            name='death_location_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='timeline.source'),
        ),
        migrations.AddField(
            model_name='person',
            name='description_sources',
            field=models.ManyToManyField(blank=True, related_name='+', to='timeline.source'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='description_sources',
            field=models.ManyToManyField(blank=True, related_name='+', to='timeline.source'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='end_date_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='timeline.source'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='location_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='timeline.source'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='start_date_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='timeline.source'),
        ),
    ]
