# Generated by Django 5.2.11 on 2026-02-24 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0018_remove_timelineevent_source_citation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='ceased_date_source_page',
        ),
        migrations.RemoveField(
            model_name='location',
            name='coordinates_source_page',
        ),
        migrations.RemoveField(
            model_name='location',
            name='established_date_source_page',
        ),
        migrations.RemoveField(
            model_name='person',
            name='birth_date_source_page',
        ),
        migrations.RemoveField(
            model_name='person',
            name='birth_location_source_page',
        ),
        migrations.RemoveField(
            model_name='person',
            name='death_date_source_page',
        ),
        migrations.RemoveField(
            model_name='person',
            name='death_location_source_page',
        ),
        migrations.RemoveField(
            model_name='timelineevent',
            name='end_date_source_page',
        ),
        migrations.RemoveField(
            model_name='timelineevent',
            name='location_source_page',
        ),
        migrations.RemoveField(
            model_name='timelineevent',
            name='start_date_source_page',
        ),
        migrations.AddField(
            model_name='source',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Optional parent source (e.g. the book this page is in)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='timeline.source'),
        ),
    ]
