# Generated by Django 5.2.11 on 2026-02-24 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0019_remove_location_ceased_date_source_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='is_default',
            field=models.BooleanField(default=False, help_text='If true, this timeline will automatically load for new visitors.'),
        ),
    ]
