# Generated by Django 5.2.11 on 2026-02-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0020_timeline_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='status',
            field=models.CharField(choices=[('verified', 'Verified'), ('unverified', 'Unverified'), ('estimate', 'Rough Estimate'), ('disputed', 'Disputed')], default='unverified', max_length=20),
        ),
        migrations.AddField(
            model_name='person',
            name='status',
            field=models.CharField(choices=[('verified', 'Verified'), ('unverified', 'Unverified'), ('estimate', 'Rough Estimate'), ('disputed', 'Disputed')], default='unverified', max_length=20),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='status',
            field=models.CharField(choices=[('verified', 'Verified'), ('unverified', 'Unverified'), ('estimate', 'Rough Estimate'), ('disputed', 'Disputed')], default='unverified', max_length=20),
        ),
    ]
