# Generated by Django 5.2.11 on 2026-02-26 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0021_location_status_person_status_timelineevent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True, help_text='\n<details style="margin-top: 0.5rem; border: 1px solid #e5e7eb; padding: 0.75rem; border-radius: 0.375rem; background-color: #f9fafb; font-size: 0.875rem;">\n    <summary style="cursor: pointer; font-weight: 600; color: #2563eb;">Markdown formatting is supported. Click here for a cheat sheet.</summary>\n    <div style="margin-top: 0.75rem; font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace; white-space: pre-wrap; color: #374151; line-height: 1.5;"># Heading 1\n## Heading 2\n**Bold Text**\n*Italic Text*\n- Bulleted item 1\n- Bulleted item 2\n1. Numbered item 1\n2. Numbered item 2\n[Link description](https://example.com)\n> Block quote text</div>\n</details>\n', null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='description',
            field=models.TextField(blank=True, help_text='\n<details style="margin-top: 0.5rem; border: 1px solid #e5e7eb; padding: 0.75rem; border-radius: 0.375rem; background-color: #f9fafb; font-size: 0.875rem;">\n    <summary style="cursor: pointer; font-weight: 600; color: #2563eb;">Markdown formatting is supported. Click here for a cheat sheet.</summary>\n    <div style="margin-top: 0.75rem; font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace; white-space: pre-wrap; color: #374151; line-height: 1.5;"># Heading 1\n## Heading 2\n**Bold Text**\n*Italic Text*\n- Bulleted item 1\n- Bulleted item 2\n1. Numbered item 1\n2. Numbered item 2\n[Link description](https://example.com)\n> Block quote text</div>\n</details>\n', null=True),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='description',
            field=models.TextField(blank=True, help_text='\n<details style="margin-top: 0.5rem; border: 1px solid #e5e7eb; padding: 0.75rem; border-radius: 0.375rem; background-color: #f9fafb; font-size: 0.875rem;">\n    <summary style="cursor: pointer; font-weight: 600; color: #2563eb;">Markdown formatting is supported. Click here for a cheat sheet.</summary>\n    <div style="margin-top: 0.75rem; font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace; white-space: pre-wrap; color: #374151; line-height: 1.5;"># Heading 1\n## Heading 2\n**Bold Text**\n*Italic Text*\n- Bulleted item 1\n- Bulleted item 2\n1. Numbered item 1\n2. Numbered item 2\n[Link description](https://example.com)\n> Block quote text</div>\n</details>\n', null=True),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='description',
            field=models.TextField(help_text='\n<details style="margin-top: 0.5rem; border: 1px solid #e5e7eb; padding: 0.75rem; border-radius: 0.375rem; background-color: #f9fafb; font-size: 0.875rem;">\n    <summary style="cursor: pointer; font-weight: 600; color: #2563eb;">Markdown formatting is supported. Click here for a cheat sheet.</summary>\n    <div style="margin-top: 0.75rem; font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace; white-space: pre-wrap; color: #374151; line-height: 1.5;"># Heading 1\n## Heading 2\n**Bold Text**\n*Italic Text*\n- Bulleted item 1\n- Bulleted item 2\n1. Numbered item 1\n2. Numbered item 2\n[Link description](https://example.com)\n> Block quote text</div>\n</details>\n'),
        ),
    ]
