# Generated by Django 5.2.11 on 2026-02-26 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0022_alter_location_description_alter_person_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#3B82F6', help_text='Hex color code (e.g. #3B82F6) or Tailwind color class', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='location',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='locations', to='timeline.tag'),
        ),
        migrations.AddField(
            model_name='person',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='people', to='timeline.tag'),
        ),
        migrations.AddField(
            model_name='source',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='sources', to='timeline.tag'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tagged_events', to='timeline.tag'),
        ),
    ]
