# Generated by Django 5.2.11 on 2026-02-26 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0023_tag_location_tags_person_tags_source_tags_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='attachments/')),
                ('file_type', models.CharField(choices=[('document', 'Document'), ('audio', 'Audio'), ('video', 'Video'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True, help_text='\n<details style="margin-top: 0.5rem; border: 1px solid #e5e7eb; padding: 0.75rem; border-radius: 0.375rem; background-color: #f9fafb; font-size: 0.875rem;">\n    <summary style="cursor: pointer; font-weight: 600; color: #2563eb;">Markdown formatting is supported. Click here for a cheat sheet.</summary>\n    <div style="margin-top: 0.75rem; font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace; white-space: pre-wrap; color: #374151; line-height: 1.5;"># Heading 1\n## Heading 2\n**Bold Text**\n*Italic Text*\n- Bulleted item 1\n- Bulleted item 2\n1. Numbered item 1\n2. Numbered item 2\n[Link description](https://example.com)\n> Block quote text</div>\n</details>\n', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('events', models.ManyToManyField(blank=True, related_name='attachments', to='timeline.timelineevent')),
                ('locations', models.ManyToManyField(blank=True, related_name='attachments', to='timeline.location')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to=settings.AUTH_USER_MODEL)),
                ('people', models.ManyToManyField(blank=True, related_name='attachments', to='timeline.person')),
                ('sources', models.ManyToManyField(blank=True, related_name='attachments', to='timeline.source')),
            ],
        ),
    ]
