# Generated by Django 5.2.11 on 2026-02-26 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0025_historicallocation_historicalperson_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='\n<details style="margin-top: 0.5rem; border: 1px solid #e5e7eb; padding: 0.75rem; border-radius: 0.375rem; background-color: #f9fafb; font-size: 0.875rem;">\n    <summary style="cursor: pointer; font-weight: 600; color: #2563eb;">Markdown formatting is supported. Click here for a cheat sheet.</summary>\n    <div style="margin-top: 0.75rem; font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace; white-space: pre-wrap; color: #374151; line-height: 1.5;"># Heading 1\n## Heading 2\n**Bold Text**\n*Italic Text*\n- Bulleted item 1\n- Bulleted item 2\n1. Numbered item 1\n2. Numbered item 2\n[Link description](https://example.com)\n> Block quote text</div>\n</details>\n', null=True)),
                ('color', models.CharField(default='#8B5CF6', help_text='Hex color code (e.g. #8B5CF6) or Tailwind color class', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('cloned_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='timeline.story')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='stories', to='timeline.tag')),
            ],
            options={
                'verbose_name_plural': 'Stories',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='StoryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(default=0, help_text='Manual override for ordering events exactly on the same date')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeline.timelineevent')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeline.story')),
            ],
            options={
                'ordering': ['sequence'],
                'unique_together': {('story', 'event')},
            },
        ),
    ]
