# Generated by Django 5.2.11 on 2026-02-26 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0026_story_storyevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallocation',
            name='needs_research',
            field=models.BooleanField(default=False, help_text='Flag for researcher follow-up'),
        ),
        migrations.AddField(
            model_name='historicallocation',
            name='researcher_notes',
            field=models.TextField(blank=True, help_text='Private notes for research follow-up', null=True),
        ),
        migrations.AddField(
            model_name='historicalperson',
            name='needs_research',
            field=models.BooleanField(default=False, help_text='Flag for researcher follow-up'),
        ),
        migrations.AddField(
            model_name='historicalperson',
            name='researcher_notes',
            field=models.TextField(blank=True, help_text='Private notes for research follow-up', null=True),
        ),
        migrations.AddField(
            model_name='historicaltimelineevent',
            name='needs_research',
            field=models.BooleanField(default=False, help_text='Flag for researcher follow-up'),
        ),
        migrations.AddField(
            model_name='historicaltimelineevent',
            name='researcher_notes',
            field=models.TextField(blank=True, help_text='Private notes for research follow-up', null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='needs_research',
            field=models.BooleanField(default=False, help_text='Flag for researcher follow-up'),
        ),
        migrations.AddField(
            model_name='location',
            name='researcher_notes',
            field=models.TextField(blank=True, help_text='Private notes for research follow-up', null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='needs_research',
            field=models.BooleanField(default=False, help_text='Flag for researcher follow-up'),
        ),
        migrations.AddField(
            model_name='person',
            name='researcher_notes',
            field=models.TextField(blank=True, help_text='Private notes for research follow-up', null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='needs_research',
            field=models.BooleanField(default=False, help_text='Flag for researcher follow-up'),
        ),
        migrations.AddField(
            model_name='source',
            name='researcher_notes',
            field=models.TextField(blank=True, help_text='Private notes for research follow-up', null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='needs_research',
            field=models.BooleanField(default=False, help_text='Flag for researcher follow-up'),
        ),
        migrations.AddField(
            model_name='story',
            name='researcher_notes',
            field=models.TextField(blank=True, help_text='Private notes for research follow-up', null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='needs_research',
            field=models.BooleanField(default=False, help_text='Flag for researcher follow-up'),
        ),
        migrations.AddField(
            model_name='tag',
            name='researcher_notes',
            field=models.TextField(blank=True, help_text='Private notes for research follow-up', null=True),
        ),
        migrations.AddField(
            model_name='timeline',
            name='needs_research',
            field=models.BooleanField(default=False, help_text='Flag for researcher follow-up'),
        ),
        migrations.AddField(
            model_name='timeline',
            name='researcher_notes',
            field=models.TextField(blank=True, help_text='Private notes for research follow-up', null=True),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='needs_research',
            field=models.BooleanField(default=False, help_text='Flag for researcher follow-up'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='researcher_notes',
            field=models.TextField(blank=True, help_text='Private notes for research follow-up', null=True),
        ),
    ]
