# Generated by Django 5.2.11 on 2026-02-27 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0027_historicallocation_needs_research_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallocation',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='historicalperson',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='historicaltimelineevent',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='historicaltimelineevent',
            name='is_auto_generated',
            field=models.BooleanField(db_index=True, default=False, help_text='True if created automatically (e.g. births/deaths)'),
        ),
        migrations.AlterField(
            model_name='historicaltimelineevent',
            name='start_date',
            field=models.DateField(db_index=True, help_text='Requires at least a start date'),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='is_auto_generated',
            field=models.BooleanField(db_index=True, default=False, help_text='True if created automatically (e.g. births/deaths)'),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='start_date',
            field=models.DateField(db_index=True, help_text='Requires at least a start date'),
        ),
    ]
