# Generated by Django 5.2.11 on 2026-02-27 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0028_remove_historicallocation_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallocation',
            name='status',
            field=models.CharField(choices=[('verified', 'Verified'), ('unverified', 'Unverified'), ('estimate', 'Rough Estimate'), ('disputed', 'Disputed')], db_index=True, default='unverified', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalperson',
            name='status',
            field=models.CharField(choices=[('verified', 'Verified'), ('unverified', 'Unverified'), ('estimate', 'Rough Estimate'), ('disputed', 'Disputed')], db_index=True, default='unverified', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicaltimelineevent',
            name='status',
            field=models.CharField(choices=[('verified', 'Verified'), ('unverified', 'Unverified'), ('estimate', 'Rough Estimate'), ('disputed', 'Disputed')], db_index=True, default='unverified', max_length=20),
        ),
        migrations.AlterField(
            model_name='location',
            name='status',
            field=models.CharField(choices=[('verified', 'Verified'), ('unverified', 'Unverified'), ('estimate', 'Rough Estimate'), ('disputed', 'Disputed')], db_index=True, default='unverified', max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.CharField(choices=[('verified', 'Verified'), ('unverified', 'Unverified'), ('estimate', 'Rough Estimate'), ('disputed', 'Disputed')], db_index=True, default='unverified', max_length=20),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='status',
            field=models.CharField(choices=[('verified', 'Verified'), ('unverified', 'Unverified'), ('estimate', 'Rough Estimate'), ('disputed', 'Disputed')], db_index=True, default='unverified', max_length=20),
        ),
    ]
