# Generated by Django 5.2.11 on 2026-03-02 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0029_alter_historicallocation_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltimelineevent',
            name='end_location',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Optional destination for travel/journeys', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='timeline.location'),
        ),
        migrations.AddField(
            model_name='historicaltimelineevent',
            name='end_location_source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='timeline.source'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='end_location',
            field=models.ForeignKey(blank=True, help_text='Optional destination for travel/journeys', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_ending_here', to='timeline.location'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='end_location_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='timeline.source'),
        ),
    ]
