# Generated by Django 5.2.11 on 2026-03-02 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0030_historicaltimelineevent_end_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalperson',
            name='burial_location',
            field=models.CharField(blank=True, help_text="Free-form text for burial site (e.g. 'Boot Hill Cemetery, Tombstone, AZ')", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalperson',
            name='burial_location_source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='timeline.source'),
        ),
        migrations.AddField(
            model_name='person',
            name='burial_location',
            field=models.CharField(blank=True, help_text="Free-form text for burial site (e.g. 'Boot Hill Cemetery, Tombstone, AZ')", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='burial_location_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='timeline.source'),
        ),
    ]
