# Generated by Django 5.2.11 on 2026-03-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0031_historicalperson_burial_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallocation',
            name='ceased_date_display',
        ),
        migrations.RemoveField(
            model_name='historicallocation',
            name='established_date_display',
        ),
        migrations.RemoveField(
            model_name='historicalperson',
            name='birth_date_display',
        ),
        migrations.RemoveField(
            model_name='historicalperson',
            name='death_date_display',
        ),
        migrations.RemoveField(
            model_name='historicaltimelineevent',
            name='end_date_display',
        ),
        migrations.RemoveField(
            model_name='historicaltimelineevent',
            name='start_date_display',
        ),
        migrations.RemoveField(
            model_name='location',
            name='ceased_date_display',
        ),
        migrations.RemoveField(
            model_name='location',
            name='established_date_display',
        ),
        migrations.RemoveField(
            model_name='person',
            name='birth_date_display',
        ),
        migrations.RemoveField(
            model_name='person',
            name='death_date_display',
        ),
        migrations.RemoveField(
            model_name='personrelationship',
            name='end_date_display',
        ),
        migrations.RemoveField(
            model_name='personrelationship',
            name='start_date_display',
        ),
        migrations.RemoveField(
            model_name='timelineevent',
            name='end_date_display',
        ),
        migrations.RemoveField(
            model_name='timelineevent',
            name='start_date_display',
        ),
        migrations.AddField(
            model_name='historicallocation',
            name='ceased_date_precision',
            field=models.CharField(blank=True, choices=[('exact', 'Exact'), ('circa', 'Circa (c.)'), ('before', 'Before (bef.)'), ('after', 'After (aft.)'), ('decade', 'Decade (e.g. 1840s)')], default='exact', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicallocation',
            name='established_date_precision',
            field=models.CharField(blank=True, choices=[('exact', 'Exact'), ('circa', 'Circa (c.)'), ('before', 'Before (bef.)'), ('after', 'After (aft.)'), ('decade', 'Decade (e.g. 1840s)')], default='exact', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalperson',
            name='birth_date_precision',
            field=models.CharField(blank=True, choices=[('exact', 'Exact'), ('circa', 'Circa (c.)'), ('before', 'Before (bef.)'), ('after', 'After (aft.)'), ('decade', 'Decade (e.g. 1840s)')], default='exact', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalperson',
            name='death_date_precision',
            field=models.CharField(blank=True, choices=[('exact', 'Exact'), ('circa', 'Circa (c.)'), ('before', 'Before (bef.)'), ('after', 'After (aft.)'), ('decade', 'Decade (e.g. 1840s)')], default='exact', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicaltimelineevent',
            name='end_date_precision',
            field=models.CharField(blank=True, choices=[('exact', 'Exact'), ('circa', 'Circa (c.)'), ('before', 'Before (bef.)'), ('after', 'After (aft.)'), ('decade', 'Decade (e.g. 1840s)')], default='exact', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicaltimelineevent',
            name='start_date_precision',
            field=models.CharField(blank=True, choices=[('exact', 'Exact'), ('circa', 'Circa (c.)'), ('before', 'Before (bef.)'), ('after', 'After (aft.)'), ('decade', 'Decade (e.g. 1840s)')], default='exact', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='ceased_date_precision',
            field=models.CharField(blank=True, choices=[('exact', 'Exact'), ('circa', 'Circa (c.)'), ('before', 'Before (bef.)'), ('after', 'After (aft.)'), ('decade', 'Decade (e.g. 1840s)')], default='exact', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='established_date_precision',
            field=models.CharField(blank=True, choices=[('exact', 'Exact'), ('circa', 'Circa (c.)'), ('before', 'Before (bef.)'), ('after', 'After (aft.)'), ('decade', 'Decade (e.g. 1840s)')], default='exact', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='birth_date_precision',
            field=models.CharField(blank=True, choices=[('exact', 'Exact'), ('circa', 'Circa (c.)'), ('before', 'Before (bef.)'), ('after', 'After (aft.)'), ('decade', 'Decade (e.g. 1840s)')], default='exact', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='death_date_precision',
            field=models.CharField(blank=True, choices=[('exact', 'Exact'), ('circa', 'Circa (c.)'), ('before', 'Before (bef.)'), ('after', 'After (aft.)'), ('decade', 'Decade (e.g. 1840s)')], default='exact', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='personrelationship',
            name='end_date_precision',
            field=models.CharField(blank=True, choices=[('exact', 'Exact'), ('circa', 'Circa (c.)'), ('before', 'Before (bef.)'), ('after', 'After (aft.)'), ('decade', 'Decade (e.g. 1840s)')], default='exact', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='personrelationship',
            name='start_date_precision',
            field=models.CharField(blank=True, choices=[('exact', 'Exact'), ('circa', 'Circa (c.)'), ('before', 'Before (bef.)'), ('after', 'After (aft.)'), ('decade', 'Decade (e.g. 1840s)')], default='exact', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='end_date_precision',
            field=models.CharField(blank=True, choices=[('exact', 'Exact'), ('circa', 'Circa (c.)'), ('before', 'Before (bef.)'), ('after', 'After (aft.)'), ('decade', 'Decade (e.g. 1840s)')], default='exact', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='start_date_precision',
            field=models.CharField(blank=True, choices=[('exact', 'Exact'), ('circa', 'Circa (c.)'), ('before', 'Before (bef.)'), ('after', 'After (aft.)'), ('decade', 'Decade (e.g. 1840s)')], default='exact', max_length=10, null=True),
        ),
    ]
