# Generated by Django 5.2.11 on 2026-03-04 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0032_replace_display_with_precision'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallocation',
            name='ceased_date_granularity',
            field=models.CharField(blank=True, choices=[('day', 'Day  (June 1, 1847)'), ('month', 'Month  (June 1847)'), ('year', 'Year  (1847)')], default='day', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicallocation',
            name='established_date_granularity',
            field=models.CharField(blank=True, choices=[('day', 'Day  (June 1, 1847)'), ('month', 'Month  (June 1847)'), ('year', 'Year  (1847)')], default='day', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalperson',
            name='birth_date_granularity',
            field=models.CharField(blank=True, choices=[('day', 'Day  (June 1, 1847)'), ('month', 'Month  (June 1847)'), ('year', 'Year  (1847)')], default='day', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalperson',
            name='death_date_granularity',
            field=models.CharField(blank=True, choices=[('day', 'Day  (June 1, 1847)'), ('month', 'Month  (June 1847)'), ('year', 'Year  (1847)')], default='day', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicaltimelineevent',
            name='end_date_granularity',
            field=models.CharField(blank=True, choices=[('day', 'Day  (June 1, 1847)'), ('month', 'Month  (June 1847)'), ('year', 'Year  (1847)')], default='day', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicaltimelineevent',
            name='start_date_granularity',
            field=models.CharField(blank=True, choices=[('day', 'Day  (June 1, 1847)'), ('month', 'Month  (June 1847)'), ('year', 'Year  (1847)')], default='day', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='ceased_date_granularity',
            field=models.CharField(blank=True, choices=[('day', 'Day  (June 1, 1847)'), ('month', 'Month  (June 1847)'), ('year', 'Year  (1847)')], default='day', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='established_date_granularity',
            field=models.CharField(blank=True, choices=[('day', 'Day  (June 1, 1847)'), ('month', 'Month  (June 1847)'), ('year', 'Year  (1847)')], default='day', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='birth_date_granularity',
            field=models.CharField(blank=True, choices=[('day', 'Day  (June 1, 1847)'), ('month', 'Month  (June 1847)'), ('year', 'Year  (1847)')], default='day', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='death_date_granularity',
            field=models.CharField(blank=True, choices=[('day', 'Day  (June 1, 1847)'), ('month', 'Month  (June 1847)'), ('year', 'Year  (1847)')], default='day', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='personrelationship',
            name='end_date_granularity',
            field=models.CharField(blank=True, choices=[('day', 'Day  (June 1, 1847)'), ('month', 'Month  (June 1847)'), ('year', 'Year  (1847)')], default='day', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='personrelationship',
            name='start_date_granularity',
            field=models.CharField(blank=True, choices=[('day', 'Day  (June 1, 1847)'), ('month', 'Month  (June 1847)'), ('year', 'Year  (1847)')], default='day', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='end_date_granularity',
            field=models.CharField(blank=True, choices=[('day', 'Day  (June 1, 1847)'), ('month', 'Month  (June 1847)'), ('year', 'Year  (1847)')], default='day', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='start_date_granularity',
            field=models.CharField(blank=True, choices=[('day', 'Day  (June 1, 1847)'), ('month', 'Month  (June 1847)'), ('year', 'Year  (1847)')], default='day', max_length=10, null=True),
        ),
    ]
