# Generated by Django 5.2.11 on 2026-03-05 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0033_add_date_granularity'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('valid_from', models.DateField(blank=True, help_text='Start date for this alias (inclusive)', null=True)),
                ('valid_to', models.DateField(blank=True, help_text='End date for this alias (inclusive)', null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='timeline.location')),
            ],
            options={
                'verbose_name_plural': 'Location Aliases',
                'ordering': ['valid_from', 'name'],
            },
        ),
    ]
