# Generated by Django 5.2.11 on 2026-03-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0035_historicaldisputedfact_disputedfact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disputedfact',
            name='field_name',
            field=models.CharField(choices=[('start_date', 'Start Date'), ('end_date', 'End Date'), ('established_date', 'Established Date'), ('ceased_date', 'Ceased Date'), ('birth_date', 'Birth Date'), ('death_date', 'Death Date'), ('description', 'Description'), ('location', 'Location'), ('name', 'Name')], help_text='Select the field that is disputed', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicaldisputedfact',
            name='field_name',
            field=models.CharField(choices=[('start_date', 'Start Date'), ('end_date', 'End Date'), ('established_date', 'Established Date'), ('ceased_date', 'Ceased Date'), ('birth_date', 'Birth Date'), ('death_date', 'Death Date'), ('description', 'Description'), ('location', 'Location'), ('name', 'Name')], help_text='Select the field that is disputed', max_length=50),
        ),
    ]
