# Generated by Django 5.2.11 on 2026-03-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0037_publiccomment_researchquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalperson',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('non-binary', 'Non-binary'), ('intersex', 'Intersex'), ('other', 'Other'), ('unknown', 'Unknown')], default='unknown', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalperson',
            name='gender_custom',
            field=models.CharField(blank=True, help_text="Specific gender identity if 'Other' is selected", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('non-binary', 'Non-binary'), ('intersex', 'Intersex'), ('other', 'Other'), ('unknown', 'Unknown')], default='unknown', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='gender_custom',
            field=models.CharField(blank=True, help_text="Specific gender identity if 'Other' is selected", max_length=100, null=True),
        ),
    ]
