# Generated by Django 5.2.11 on 2026-04-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0039_helpcategory_helptopic_helpimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallocation',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Check to hide this item from public view'),
        ),
        migrations.AddField(
            model_name='historicalperson',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Check to hide this item from public view'),
        ),
        migrations.AddField(
            model_name='historicaltimelineevent',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Check to hide this item from public view'),
        ),
        migrations.AddField(
            model_name='location',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Check to hide this item from public view'),
        ),
        migrations.AddField(
            model_name='person',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Check to hide this item from public view'),
        ),
        migrations.AddField(
            model_name='story',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Check to hide this item from public view'),
        ),
        migrations.AddField(
            model_name='timeline',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Check to hide this item from public view'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Check to hide this item from public view'),
        ),
    ]
