# Generated by Django 5.2.11 on 2026-04-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0040_historicallocation_is_private_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Check to hide this item from public view'),
        ),
    ]
