# Generated by Django 5.2.11 on 2026-04-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0041_source_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchquestion',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], db_index=True, default='medium', max_length=10),
        ),
    ]
