import json
import io
from typing import List, Dict, Any
from ..models import TimelineEvent, Location, Person, Tag, Story, StoryEvent
from django.utils.dateparse import parse_date

class JsonEventImporter:
    """
    Importer for Timeline Events JSON format.
    Expects a list of event dictionaries specifically in the format generated by export_json.
    """
    def __init__(self, user=None):
        self.user = user

    def parse(self, file_obj) -> List[Dict[str, Any]]:
        if isinstance(file_obj, bytes):
            content = file_obj.decode('utf-8')
        elif hasattr(file_obj, 'read'):
            content = file_obj.read()
            if isinstance(content, bytes):
                content = content.decode('utf-8')
        else:
            content = file_obj
            
        return json.loads(content)

    def import_data(self, file_obj):
        parsed_data = self.parse(file_obj)
        created_count = 0
        errors = []

        # Support 'Full Archive' format (dict) and legacy 'List' format
        if isinstance(parsed_data, dict) and 'events' in parsed_data:
            event_list = parsed_data['events']
        elif isinstance(parsed_data, list):
            event_list = parsed_data
        else:
            return 0, ["JSON payload must be a list of event objects or a valid Archive dictionary."]

        for row in event_list:
            try:
                self.create_record(row)
                created_count += 1
            except Exception as e:
                errors.append(f"Error importing event '{row.get('title', 'Unknown')}': {str(e)}")
        
        return created_count, errors

    def _resolve_date(self, data: Dict, date_key: str):
        """
        Resolve a date from the JSON event dict.

        Returns the parsed date or None.
        """
        raw = data.get(date_key)
        if not raw:
            return None

        # Try standard ISO
        return parse_date(str(raw))

    def create_record(self, data: Dict[str, Any]):
        if not data.get('title'):
            raise ValueError("Event is missing a title.")

        location = None
        if data.get('location'):
            location_name = data['location'].strip() if isinstance(data['location'], str) else data['location'].get('name', '').strip()
            if location_name:
                location, _ = Location.objects.get_or_create(name=location_name)

        people = []
        if data.get('people'):
            for p_dict in data['people']:
                person_name = p_dict.get('name', '').strip() if isinstance(p_dict, dict) else str(p_dict).strip()
                if person_name:
                    person, _ = Person.objects.get_or_create(name=person_name)
                    people.append(person)

        tags = []
        if data.get('tags'):
            for t_dict in data['tags']:
                tag_name = t_dict.get('name', '').strip() if isinstance(t_dict, dict) else str(t_dict).strip()
                if tag_name:
                    tag, _ = Tag.objects.get_or_create(
                        name=tag_name,
                        defaults={'color': t_dict.get('color', 'bg-gray-500') if isinstance(t_dict, dict) else 'bg-gray-500'}
                    )
                    tags.append(tag)

        # Parse dates
        start_date = self._resolve_date(data, 'start_date')
        if not start_date:
            # Try the 'start' key (vis.js ISO format from serialised events)
            start_date = self._resolve_date(data, 'start')
        if not start_date:
            start_date_str = '1900-01-01'
            start_date = parse_date(start_date_str)

        end_date = self._resolve_date(data, 'end_date')
        if not end_date:
            end_date = self._resolve_date(data, 'end')

        try:
            event = TimelineEvent.objects.create(
                title=data['title'],
                description=data.get('description', ''),
                start_date=start_date,
                end_date=end_date,
                location=location,
                owner=self.user if self.user and self.user.is_authenticated else None
            )
        except Exception as e:
            print(f"FAILED TO CREATE EVENT: {data}")
            print(f"start_date was: {start_date}")
            raise e
            
        if people:
            event.people.set(people)
        if tags:
            event.tags.set(tags)
            
        # Handle Stories
        if data.get('stories'):
            for s_dict in data['stories']:
                story_name = s_dict.get('name', '') or s_dict.get('title', '')
                story_name = story_name.strip() if story_name else ''
                if story_name:
                    story, _ = Story.objects.get_or_create(
                        name=story_name,
                        owner=self.user if self.user and self.user.is_authenticated else None
                    )
                    StoryEvent.objects.get_or_create(
                        story=story,
                        event=event,
                        defaults={'sequence': s_dict.get('sequence', 0)}
                    )
            
        return event
