"""
Django settings for timeline_project project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path
from urllib.parse import quote_plus
from dotenv import load_dotenv
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(os.path.join(BASE_DIR, '.env'), override=True)

def pull_secrets_from_manager():
    """
    Pulls secrets from Google Secret Manager conditionally based on enabled features.
    Ensures safe URL encoding for database credentials.
    """
    if os.getenv('USE_SECRET_MANAGER', 'False') == 'True':
        project_id = os.getenv('GCP_PROJECT_ID')
        if not project_id:
            return

        try:
            from google.cloud import secretmanager
            client = secretmanager.SecretManagerServiceClient()

            def get_secret(secret_name):
                try:
                    name = f"projects/{project_id}/secrets/{secret_name}/versions/latest"
                    response = client.access_secret_version(request={"name": name})
                    return response.payload.data.decode("UTF-8").strip()
                except Exception:
                    return None

            # 1. CORE: Always needed for production
            for core in ['DATABASE_URL', 'SECRET_KEY', 'ALLOWED_HOSTS']:
                val = get_secret(core)
                if val:
                    os.environ[core] = val

            # 2. OPTIONAL Features
            if os.getenv('USE_GCS', 'False') == 'True':
                val = get_secret('GS_BUCKET_NAME')
                if val:
                    os.environ['GS_BUCKET_NAME'] = val

            if os.getenv('USE_REDIS', 'False') == 'True':
                val = get_secret('REDIS_URL')
                if val:
                    os.environ['REDIS_URL'] = val

            if os.getenv('USE_GOOGLE_OAUTH', 'False') == 'True':
                for oauth in ['GOOGLE_CLIENT_ID', 'GOOGLE_CLIENT_SECRET']:
                    val = get_secret(oauth)
                    if val:
                        os.environ[oauth] = val
                    else:
                        sys.stderr.write(f"--- WARNING: Secret '{oauth}' not found in Secret Manager ---\n")

        except Exception as e:
            sys.stderr.write(f"--- SECRET MANAGER ERROR: {str(e)} ---\n")
            pass

# Perform Secret Manager pull before other settings are evaluated
pull_secrets_from_manager()



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-z9ko8q%m=x!=&q^93s#0x0*dktfwd@170*qtrwrj#ax9k5ze(+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'

# ALLOWED_HOSTS derived from Secret Manager / Environment
ALLOWED_HOSTS = [host.strip() for host in os.getenv('ALLOWED_HOSTS', '').split(',') if host.strip()]
ALLOWED_HOSTS += ['localhost', '127.0.0.1', '.a.run.app']

# Production Hardening
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = False
    CSRF_TRUSTED_ORIGINS = [f"https://{host}" for host in ALLOWED_HOSTS if host != '*' and not host.startswith('.')]
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'timeline',
    'simple_history',
    'background_task',
]

# Auth Pillar 1: Identity-Aware Proxy (IAP)
USE_IAP = os.getenv('USE_IAP', 'False') == 'True'

# Auth Pillar 2: Google OAuth2 (Social Login)
USE_GOOGLE_OAUTH = os.getenv('USE_GOOGLE_OAUTH', 'False') == 'True'

if USE_GOOGLE_OAUTH:
    INSTALLED_APPS.append('social_django')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
]

# Insert Google OAuth Middleware if enabled
if USE_GOOGLE_OAUTH:
    MIDDLEWARE.append('social_django.middleware.SocialAuthExceptionMiddleware')

# Insert IAP Middleware if enabled
if USE_IAP:
    MIDDLEWARE.append('timeline.middleware.IAPMiddleware')

MIDDLEWARE += [
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
]

# Set Referrer Policy so map tiles properly load (OpenStreetMap requires a referer)
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

ROOT_URLCONF = 'timeline_project.urls'

# Authentication Backends
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

if USE_GOOGLE_OAUTH:
    AUTHENTICATION_BACKENDS.insert(0, 'social_core.backends.google.GoogleOAuth2')
    SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = os.getenv('GOOGLE_CLIENT_ID')
    SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = os.getenv('GOOGLE_CLIENT_SECRET')
    
    # Force HTTPS for the social-auth redirect URI
    SOCIAL_AUTH_REDIRECT_IS_HTTPS = True
    SOCIAL_AUTH_URL_NAMESPACE = 'social'
    
    # Auth behavior settings
    LOGIN_URL = '/auth/login/google-oauth2/'
    LOGIN_REDIRECT_URL = '/admin/'
    LOGOUT_REDIRECT_URL = '/'

# Proxy Awareness (Critical for Cloud Run HTTPS)
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
                'timeline.context_processors.auth_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'timeline_project.wsgi.application'


# Database configuration
DATABASE_URL_STR = os.getenv('DATABASE_URL')

if DATABASE_URL_STR:
    if 'sqlite' in DATABASE_URL_STR:
        DATABASES = {
            'default': dj_database_url.config(default=DATABASE_URL_STR, conn_max_age=600)
        }
    else:
        # Robust manual parsing for Cloud SQL URLs that may contain special characters (#, %, $) in passwords
        try:
            import re
            # Expected format: postgres://USER:PASSWORD@/DBNAME?host=/cloudsql/INSTANCE
            pattern = r'postgres://(?P<user>[^:]+):(?P<password>.+)@/(?P<name>[^?]+)\?host=(?P<host>.+)'
            match = re.search(pattern, DATABASE_URL_STR)
            
            if match:
                db_data = match.groupdict()
                DATABASES = {
                    'default': {
                        'ENGINE': 'django.db.backends.postgresql',
                        'NAME': db_data['name'],
                        'USER': db_data['user'],
                        'PASSWORD': db_data['password'],
                        'HOST': db_data['host'],
                        'PORT': '',
                        'CONN_MAX_AGE': 600,
                    }
                }
            else:
                # Fallback to standard dj_database_url if regex doesn't match
                DATABASES = {'default': dj_database_url.config(default=DATABASE_URL_STR, conn_max_age=600)}
        except Exception:
            DATABASES = {'default': dj_database_url.config(default=DATABASE_URL_STR, conn_max_age=600)}
else:
    # No DATABASE_URL found, use local SQLite as final fallback
    DATABASES = {
        'default': dj_database_url.config(
            default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
            conn_max_age=600,
        )
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Caching Configuration
if os.getenv('USE_REDIS', 'False') == 'True':
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/1'),
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            }
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'unique-snowflake',
        }
    }


# Static files & Media Storage
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / 'static']

# Use WhiteNoise for serving compressed static files
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Media Storage
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

if os.getenv('USE_GCS', 'False') == 'True':
    from datetime import timedelta
    # Media files (user uploads) — private bucket with signed URLs.
    GS_PROJECT_ID = os.getenv('GCP_PROJECT_ID', 'bg-helpers')
    GS_BUCKET_NAME = os.getenv('GS_BUCKET_NAME', 'timewrit-assets-bg-helpers')
    
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.gcloud.GoogleCloudStorage",
            "OPTIONS": {
                "bucket_name": GS_BUCKET_NAME,
                "project_id": GS_PROJECT_ID,
                "location": "media",
                "querystring_auth": True,
                "default_acl": None,
                "expiration": timedelta(hours=1),
                "object_parameters": {
                    "Cache-Control": "private, max-age=3600",
                },
            },
        },
        # Static assets (CSS/JS) stay on WhiteNoise — no GCS bucket needed
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }


# Logging & Monitoring
if os.getenv('USE_CLOUD_LOGGING', 'False') == 'True':
    try:
        import google.cloud.logging
        client = google.cloud.logging.Client()
        client.setup_logging()
    except Exception:
        pass

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
